# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 9, 5, 25, 144000)),
        ),
    ]
